name: Dummy CI Checks

on:
  pull_request:
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Fake lint
        run: echo "lint ok"

  unit-tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Fake unit tests
        run: |
          echo "running unit tests"
          echo "unit tests ok"

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Fake integration tests
        run: |
          echo "integration tests ok"

