name: Periodic PR merging

on:
  schedule:
  - cron: "*/5 * * * *" # every 5 minutes

jobs:
  reconcile:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce LGTM policy
        uses: jpmcb/prow-github-actions@v2.0.0
        with:
          jobs: lgtm
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: 'squash'
